# Data Analysis

## Imports

In [1]:
from __future__ import annotations

from typing import Any
from re import findall

import numpy as np
import pandas as pd

import pickle
import os

## Get files

In [2]:
## Get last run
runs = tuple(os.walk("results"))[0][1]
runs.sort()
last_run = runs[-1]
last_run

'1651674464'

In [3]:
# Get last run files
files = tuple(os.walk(f"results/{last_run}"))[0][2]
files

['9.pickle',
 '5.pickle',
 '10.pickle',
 '12.pickle',
 '7.pickle',
 '16.pickle',
 '20.pickle',
 '3.pickle',
 '1.pickle',
 '18.pickle',
 '14.pickle',
 '11.pickle',
 '8.pickle',
 '4.pickle',
 '6.pickle',
 '13.pickle',
 '2.pickle',
 '17.pickle',
 '19.pickle',
 '15.pickle']

In [4]:
# Open files in DATA
RAW_DATA: dict[int, Any] = {}

for file_name in files:
    with open(f"results/{last_run}/{file_name}", "rb") as f:
        RAW_DATA[int(findall(r"[\d+]", file_name)[0])] = pickle.load(f)

## Convert to analyzable data

In [19]:
def convert_to_waiting_matrix(state_history: list):
    print(state_history[0][0]["waiting"].shape[0])
    length = len(state_history)
    # waiting_matrix = np.zeros((state_history[0][0]["waiting"].shape[0], state_history[0][0]["waiting"].shape[1], state_history[], length))
    pass

def convert_to_elevator_matrix():
    pass

In [21]:
DATA: dict = {}

for r_data in RAW_DATA.items():
    dwell_time, d = r_data
    convert_to_waiting_matrix(d["state_history"])
    # print(r_data)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
